on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    uses: BPanther-2000/SNAP-BONGOCAT/.github/workflows/build-user-config.yml@main

